from aiogram.utils.helper import Helper, HelperMode, ListItem
from aiogram.dispatcher import FSMContext
from aiogram.dispatcher.filters import Text
from aiogram.dispatcher.filters.state import State, StatesGroup

class States(StatesGroup):
    mode = HelperMode.snake_case

    SANDBOX = State()
    AFT_INIT_STATE = State()
    TO_ME_ST = State()
    GEO_PROVE = State()
    GEO_CMPLT = State()
    COST = State()
    FLOWER_CATALOG = State()
    DATETIME1 = State()
    DATETIME2 = State()
    DATETIME3 = State()
    default_buckets = State()
    default_buckets_cap = State()
    default_buckets_categ = State()
    default_buckets_cost = State()
    default_buckets_prove = State()

    PHONE = State()
    INVOICE = State()
    AFTER_INVOICE = State()
    SHOP_GEO = State()
    FIND_SHOP = State()
    CURRENT_SHOP = State()
    INVOICE_SENDED = State()
    IGNORE = State()
    TRUE_ORDERING = State()
    SHOP_GEO_PROVE = State()
    CART = State()
    ORDERING_BUCKET = State()
    ONLY_PHONE = State()
    NS0 = State()
    NS1 = State()
    NS2 = State()
    NS3 = State()
    NS4 = State()
    UPLOAD1 = State()
    UPLOAD2 = State()
    UPLOAD3 = State()
    UPLOAD4 = State()
    UPLOAD5 = State()
    UPLOAD6 = State()
    UPLOAD7 = State()
    UPLOAD8 = State()
    MAILER = State()
    FAST_SEARCH = State()
    FAST_SEARCH_CATALOG = State()
    TO_ME_ST_test = State()
    Not_Inst = State()
    Not_Inst1 = State()
    Not_Inst2 = State()
    Not_Inst3 = State()

    manager_mode = State()

    manager_mode_edit_product = State()

    manager_mode2 = State()
    manager_mode3 = State()
    manager_mode4 = State()
    manager_mode5 = State()
    manager_mode6 = State()
    manager_mode7 = State()
    manager_mode8 = State()

    manager_mode_reg = State()
    manager_mode_reg1 = State()
    manager_mode_reg2 = State()
    manager_mode_reg3 = State()
    manager_mode_reg4 = State()
    manager_mode_reg5 = State()
    manager_mode_reg6 = State()
    manager_mode_reg7 = State()
    manager_mode_reg8 = State()
    manager_mode_reg9 = State()
    manager_mode_reg10 = State()
    manager_mode_reg11 = State()
    manager_mode_reg12 = State()
    manager_mode_reg13 = State()
    manager_mode_reg14 = State()
    manager_mode_reg15 = State()
    manager_mode_reg16 = State()
    manager_mode_reg17 = State()
    manager_mode_reg18 = State()
    manager_mode_reg19 = State()
    wait_for_delivery_cost = State()

    sales1 = State()
    sales2 = State()

    auctions = State()
    auctions1 = State()

    HOME_NUM = State()